# Porta do servidor (padrão 8080, pode mudar se quiser)
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/scoa
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect